name: ShellCheck Linter

on:
  push:
    branches:
      - main
      - master
      - kirkstone
  pull_request:
    branches:
      - main
      - master
      - kirkstone

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install ShellCheck
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # Step 3: Run ShellCheck only if .sh files exist
      - name: Run ShellCheck
        run: |
          FILES=$(find . -type f -name "*.sh")
          if [ -n "$FILES" ]; then
            echo "$FILES" | xargs shellcheck
          else
            echo "No shell scripts found, skipping ShellCheck."
          fi
